server:
  name: iam
  port: 8099
  env: prod

log:
  default:
    service: iam
    module: default
    level: info
    writer: file
    dir: ../../../log
    extra_keys:
      - requestId
  gorm:
    service: iam
    module: gorm
    level: info
    writer: file
    dir: ../../../log
    extra_keys:
      - requestId
  redis:
    service: iam
    module: redis
    level: info
    writer: file
    dir: ../../../log
    extra_keys:
      - requestId
  es:
    service: iam
    module: es
    level: info
    writer: file
    dir: ../../../log
    extra_keys:
      - requestId

mysql_configs:
  - addr: host.docker.internal:3306
    user: root
    password: 123456
    database: practice
    charset: utf8mb4
    timeout: 5s
    read_timeout: 3s
    write_timeout: 3s

redis_config:
  service: iam
  addr: 127.0.0.1:6379
  password: 123456
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

es_configs:
  - service: iam
    addr: http://host.docker.internal:9200